environment: prod
model: RSMV2
inputDataS3Bucket: thetradedesk-mlplatform-us-east-1
customInputDataPath: None
subFolderKey: split
subFolderValue: Population
syntheticIdLength: 500
inputDataS3Path: data/prod/audience/RSMV2/Imp_Seed_None/v=1
audienceJarBranch: master
audienceJarVersion: latest
