tmpNonSenEmbeddingDataS3Path: configdata/prod/audience/embedding_temp/RSMV2/nonsensitive/v=1
tmpSenEmbeddingDataS3Path: configdata/prod/audience/embedding_temp/RSMV2/sensitive/v=1
embeddingDataS3Path: configdata/prod/audience/embedding/RSMV2/v=1
inferenceDataS3Path: data/prod/audience/RSMV2/prediction
