job_name: PopulationInputDataGeneratorJob
environment: prod
model: "RSMV2"
inputDataS3Bucket: "thetradedesk-mlplatform-us-east-1"
inputDataS3Path: "data/prod/audience/RSMV2/Imp_Seed_None/v=1"
populationOutputData3Path: "data/prod/audience/RSMV2/Seed_None/v=1"
customInputDataPath: "None"
subFolderKey: "split"
subFolderValue: "Population"
syntheticIdLength: 500
