environment: prod
model: RSMV2
featureStoreReadEnv: prod
useTmpFeatureGenerator: false
extraSamplingThreshold: 0.05
rsmV2FeatureSourcePath: /featuresV2.json
subFolder: Full
densityFeatureReadPathWithoutSlash: profiles/source=bidsimpression/index=TDID/job=DailyTDIDDensityScoreSplitJob/v=1
sensitiveFeatureColumns: ''
persistHoldoutSet: true
optInSeedType: Active
optInSeedFilterExpr: 'true'
posNegRatio: 50
lowerLimitPosCntPerSeed: 200
rsmV2UserSampleSalt: TRM
rsmV2PopulationUserSampleIndex: 3,5,7
rsmV2UserSampleRatio: 1
samplerName: RSMV2
overrideMode: false
splitRemainderHashSalt: split_RSMV2
upLimitPosCntPerSeed: 40000
saveIntermediateResult: false
intermediateResultBasePathEndWithoutSlash: thetradedesk-mlplatform-us-east-1/users/yixuan.zheng/allinone/dataset/Full
maxLabelLengthPerRow: 50
minRowNumsPerPartition: 100000
trainValHoldoutTotalSplits: 10
activeSeedIdWhiteList: ''
